### ISSUE TITLE
HP Elitedesk 800 G2 SFF

### ISSUE THREAD

**Issue by ilium007** [Wamphyre/HP-ELITEDESK-800-G2-DM-MINI-HACKINTOSH-35W#1]
Any ideas for getting a SFF HP Elitedesk 800 G2 working with this?

**Comment by Wamphyre** [comment]
Just read the config.plist, there's an example you can use. For legal reasons I can't blow that information publicly.

**Comment by frank6311** [comment]
Kool thanks

**Comment by mianmuzammal196** [comment]
Hey i have the same model SFF, how did you manage to run macOS? can you guide me as well
i opened this [issue](https://github.com/Wamphyre/HP-ELITEDESK-800-G2-DM-MINI-HACKINTOSH-35W/issues/7)
